### ISSUE TITLE
hashlookup lookup via pyHIDS? 

### ISSUE THREAD

**Issue by adulau** [cedricbonhomme/pyHIDS#3]
As there is the bloomfilter available in [hashlookup](https://hashlookup.io), it might be useful to include the hash check in pyHIDS?

**Comment by cedricbonhomme** [comment]
I think that I will add a dedicated command to pyHIDS which will query hashlookup on the set of hashes (in the database of pyHIDS).

**Comment by cedricbonhomme** [comment]
![signal-2023-08-02-112829_002](https://github.com/cedricbonhomme/pyHIDS/assets/465400/90bb82ef-bc21-4a13-b87a-6fa1a702eb4c)

first draft version

**Comment by cedricbonhomme** [comment]
https://github.com/cedricbonhomme/pyHIDS/releases/tag/v0.6.0
